core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Core:index }

core_movie:
    path:     /movie
    defaults: { _controller: CoreBundle:Core:movie }

core_serie:
    path:     /serie
    defaults: { _controller: CoreBundle:Core:serie }

core_stream:
    path:     /stream/{id}
    defaults: { _controller: CoreBundle:Core:stream }

core_search:
    path:    /search
    defaults: { _controller: CoreBundle:Search:search }

core_test:
    path:    /test
    defaults: { _controller: CoreBundle:Core:test }