user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

edit_image:
    path: /profile/EditImage
    defaults:
        _controller: UserBundle:Profile:EditImage

edit_email:
    path: /profile/EditEmail
    defaults:
        _controller: UserBundle:Profile:EditEmail

forget_password:
    path: /forgetpwd
    defaults:
        _controller : UserBundle:Security:ForgetPWD
