services:
    security.login.success_handler:
        class:  UserBundle\Handler\LoginSuccessHandler
    security.login.failure_handler:
        class:  UserBundle\Handler\LoginFailureHandler
    redirect_register_user.registration.completed:
        class: UserBundle\EventListener\RegistrationConfirmListener
        arguments: [@router]
        tags:
            - { name: kernel.event_susbcriber }
